/** ISO-4217 currency codes */
export const CURRENCY = {
  amd: { code: 'amd', name: 'Armenian Dram', sign: '֏' },
  rub: { code: 'rub', name: 'Russian Ruble', sign: '₽' },
  usd: { code: 'usd', name: 'US Dollar', sign: '$' },
  eur: { code: 'eur', name: 'Euro', sign: '€' },
  gel: { code: 'gel', name: 'Georgian Lari', sign: '₾' },
  aed: { code: 'aed', name: 'Arab Emirates dirham', sign: 'DH' },
  byn: { code: 'byn', name: 'Belarusian Ruble', sign: 'Bn' },
  cad: { code: 'cad', name: 'Canadian Dollar', sign: 'C$' },
  czk: { code: 'czk', name: 'Czech koruna', sign: 'Kč' },
  gbp: { code: 'gbp', name: 'British Pound', sign: '£' },
  kzt: { code: 'kzt', name: 'Kazakhstani Tenge', sign: '₸' },
  rsd: { code: 'rsd', name: 'Serbian dinar' },
  thb: { code: 'thb', name: 'Thai baht', sign: '฿' },
  try: { code: 'try', name: 'Turkish lira', sign: '₺' },
  uah: { code: 'uah', name: 'Ukrainian Hryvnia', sign: '₴' },
  vnd: { code: 'vnd', name: 'Vietnamese Dong', sign: '₫' },
  afn: { code: 'afn', name: 'Afghan afghani' },
  all: { code: 'all', name: 'Albanian lek' },
  aoa: { code: 'aoa', name: 'Angolan kwanza' },
  ars: { code: 'ars', name: 'Argentine peso' },
  aud: { code: 'aud', name: 'Australian dollar' },
  awg: { code: 'awg', name: 'Aruban florin' },
  azn: { code: 'azn', name: 'Azerbaijani manat' },
  bam: { code: 'bam', name: 'Bosnia and Herzegovina mark' },
  bbd: { code: 'bbd', name: 'Barbados dollar' },
  bdt: { code: 'bdt', name: 'Bangladeshi taka' },
  bgn: { code: 'bgn', name: 'Bulgarian lev' },
  bhd: { code: 'bhd', name: 'Bahraini dinar' },
  bif: { code: 'bif', name: 'Burundian franc' },
  bmd: { code: 'bmd', name: 'Bermudian dollar' },
  bnd: { code: 'bnd', name: 'Brunei dollar' },
  bob: { code: 'bob', name: 'Boliviano' },
  brl: { code: 'brl', name: 'Brazilian real' },
  bsd: { code: 'bsd', name: 'Bahamian dollar' },
  btn: { code: 'btn', name: 'Bhutanese ngultrum	' },
  bwp: { code: 'bwp', name: 'Botswana pula' },
  bzd: { code: 'bzd', name: 'Belize dollar' },
  cdf: { code: 'cdf', name: 'Congolese franc' },
  chf: { code: 'chf', name: 'Swiss franc' },
  clp: { code: 'clp', name: 'Chilean peso' },
  cny: { code: 'cny', name: 'Renminbi' },
  cop: { code: 'cop', name: 'Colombian peso' },
  crc: { code: 'crc', name: 'Costa Rican colon' },
  cup: { code: 'cup', name: 'Cuban peso' },
  cve: { code: 'cve', name: 'Cape Verdean escudo' },
  djf: { code: 'djf', name: 'Djiboutian franc' },
  dkk: { code: 'dkk', name: 'Danish krone' },
  dop: { code: 'dop', name: 'Dominican peso' },
  dzd: { code: 'dzd', name: 'Algerian dinar' },
  egp: { code: 'egp', name: 'Egyptian pound' },
  ern: { code: 'ern', name: 'Eritrean nakfa' },
  etb: { code: 'etb', name: 'Ethiopian birr' },
  fjd: { code: 'fjd', name: 'Fiji dollar' },
  fkp: { code: 'fkp', name: 'Falkland Islands pound' },
  ghs: { code: 'ghs', name: 'Ghanaian cedi' },
  gip: { code: 'gip', name: 'Gibraltar pound' },
  gmd: { code: 'gmd', name: 'Gambian dalasi' },
  gnf: { code: 'gnf', name: 'Guinean franc' },
  gtq: { code: 'gtq', name: 'Guatemalan quetzal' },
  gyd: { code: 'gyd', name: 'Guyanese dollar' },
  hkd: { code: 'hkd', name: 'Hong Kong dollar' },
  hnl: { code: 'hnl', name: 'Honduran lempira' },
  htg: { code: 'htg', name: 'Haitian gourde' },
  huf: { code: 'huf', name: 'Hungarian forint' },
  idr: { code: 'idr', name: 'Indonesian rupiah' },
  ils: { code: 'ils', name: 'Israeli new shekel' },
  inr: { code: 'inr', name: 'Indian rupee' },
  iqd: { code: 'iqd', name: 'Iraqi dinar' },
  irr: { code: 'irr', name: 'Iranian rial' },
  isk: { code: 'isk', name: 'Icelandic króna' },
  jmd: { code: 'jmd', name: 'Jamaican dollar' },
  jod: { code: 'jod', name: 'Jordanian dinar' },
  jpy: { code: 'jpy', name: 'Japanese yen' },
  kes: { code: 'kes', name: 'Kenyan shilling' },
  kgs: { code: 'kgs', name: 'Kyrgyzstani som' },
  khr: { code: 'khr', name: 'Cambodian riel' },
  kmf: { code: 'kmf', name: 'Comoro franc' },
  kpw: { code: 'kpw', name: 'North Korean won' },
  krw: { code: 'krw', name: 'South Korean won' },
  kwd: { code: 'kwd', name: 'Kuwaiti dinar' },
  kyd: { code: 'kyd', name: 'Cayman Islands dollar' },
  lak: { code: 'lak', name: 'Lao kip' },
  lbp: { code: 'lbp', name: 'Lebanese pound' },
  lkr: { code: 'lkr', name: 'Sri Lankan rupee' },
  lrd: { code: 'lrd', name: 'Liberian dollar' },
  lsl: { code: 'lsl', name: 'Lesotho loti' },
  lyd: { code: 'lyd', name: 'Libyan dinar' },
  mad: { code: 'mad', name: 'Moroccan dirham' },
  mdl: { code: 'mdl', name: 'Moldovan leu' },
  mga: { code: 'mga', name: 'Malagasy ariary' },
  mkd: { code: 'mkd', name: 'Macedonian denar' },
  mmk: { code: 'mmk', name: 'Myanmar kyat' },
  mnt: { code: 'mnt', name: 'Mongolian tögrög' },
  mop: { code: 'mop', name: 'Macanese pataca' },
  mru: { code: 'mru', name: 'Mauritanian ouguiya' },
  mur: { code: 'mur', name: 'Mauritian rupee' },
  mvr: { code: 'mvr', name: 'Maldivian rufiyaa' },
  mwk: { code: 'mwk', name: 'Malawian kwacha' },
  mxn: { code: 'mxn', name: 'Mexican peso' },
  myr: { code: 'myr', name: 'Malaysian ringgit' },
  mzn: { code: 'mzn', name: 'Mozambican metical' },
  nad: { code: 'nad', name: 'Namibian dollar' },
  ngn: { code: 'ngn', name: 'Nigerian naira' },
  nio: { code: 'nio', name: 'Nicaraguan córdoba' },
  nok: { code: 'nok', name: 'Norwegian krone' },
  npr: { code: 'npr', name: 'Nepalese rupee' },
  nzd: { code: 'nzd', name: 'New Zealand dollar' },
  omr: { code: 'omr', name: 'Omani rial' },
  pab: { code: 'pab', name: 'Panamanian balboa' },
  pen: { code: 'pen', name: 'Peruvian sol' },
  pgk: { code: 'pgk', name: 'Papua New Guinean kina' },
  php: { code: 'php', name: 'Philippine peso' },
  pkr: { code: 'pkr', name: 'Pakistani rupee' },
  pln: { code: 'pln', name: 'Polish złoty' },
  pyg: { code: 'pyg', name: 'Paraguayan guaraní' },
  qar: { code: 'qar', name: 'Qatari riyal' },
  ron: { code: 'ron', name: 'Romanian leu' },
  rwf: { code: 'rwf', name: 'Rwandan franc' },
  sar: { code: 'sar', name: 'Saudi riyal' },
  sbd: { code: 'sbd', name: 'Solomon Islands dollar' },
  scr: { code: 'scr', name: 'Seychelles rupee' },
  sdg: { code: 'sdg', name: 'Sudanese pound' },
  sek: { code: 'sek', name: 'Swedish krona' },
  sgd: { code: 'sgd', name: 'Singapore dollar' },
  shp: { code: 'shp', name: 'Saint Helena pound' },
  sle: { code: 'sle', name: 'Sierra Leonean leone' },
  sos: { code: 'sos', name: 'Somalian shilling' },
  srd: { code: 'srd', name: 'Surinamese dollar' },
  stn: { code: 'stn', name: 'São Tomé and Príncipe dobra' },
  svc: { code: 'svc', name: 'Salvadoran colón' },
  syp: { code: 'syp', name: 'Syrian pound' },
  szl: { code: 'szl', name: 'Swazi lilangeni' },
  tjs: { code: 'tjs', name: 'Tajikistani somoni' },
  tmt: { code: 'tmt', name: 'Turkmenistan manat' },
  tnd: { code: 'tnd', name: 'Tunisian dinar' },
  top: { code: 'top', name: 'Tongan paʻanga' },
  ttd: { code: 'ttd', name: 'Trinidad and Tobago dollar' },
  twd: { code: 'twd', name: 'New Taiwan dollar' },
  tzs: { code: 'tzs', name: 'Tanzanian shilling' },
  ugx: { code: 'ugx', name: 'Ugandan shilling' },
  uyu: { code: 'uyu', name: 'Uruguayan peso' },
  uzs: { code: 'uzs', name: 'Uzbekistani sum' },
  ved: { code: 'ved', name: 'Venezuelan digital bolívar' },
  ves: { code: 'ves', name: 'Venezuelan sovereign bolívar' },
  vuv: { code: 'vuv', name: 'Vanuatu vatu' },
  wst: { code: 'wst', name: 'Samoan tala' },
  yer: { code: 'yer', name: 'Yemeni rial' },
  zar: { code: 'zar', name: 'South African rand' },
  zmw: { code: 'zmw', name: 'Zambian kwacha' },
  zwl: { code: 'zwl', name: 'Zimbabwean dollar' },

  // btc: { code: 'btc', name: 'Bitcoin', sign: "₿" },
  // eth: { code: 'eth', name: 'Ethereum', sign: "Ξ" },
} as const
